import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  console.log(user);
  if (!user) {
    return <SignIn />;
  }

  return (
    <div className="flex">
      <img
        className="h-14 w-14 rounded-full"
        src={user.profileImageUrl}
        alt="profile_image"
      />
      <input
        placeholder="What's on your mind?"
        className="ml-4 w-full bg-transparent"
      />
    </div>
  );
};

const Home: NextPage = () => {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const { data } = api.post.getAll.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400  md:max-w-2xl">
          <div className=" border-b border-slate-400 p-4">
            {!user.isSignedIn ? <SignInButton /> : <CreatePostWizard />}
          </div>
          <div>
            {data?.map((post) => (
              <div key={post.id} className="border-b border-slate-400 p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
